Models/MoreDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NETD3202_Lab5_V3.Models
{
    public class MoreDetail
    {
        [Key]
        public int gID { get; set; }
        public string description { get; set; }
        [ForeignKey("gID")]
        public VideoGame gameID { get; set; }
    }
}

Controllers/MoreDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NETD3202_Lab5_V3.Data;
using NETD3202_Lab5_V3.Models;

namespace NETD3202_Lab5_V3.Controllers
{
    public class MoreDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoreDetailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MoreDetails
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.MoreDetails.Include(m => m.gameID);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: MoreDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View(nameof(UnknownID));
            }

            var moreDetail = await _context.MoreDetails
                .Include(m => m.gameID)
                .FirstOrDefaultAsync(m => m.gID == id);
            if (moreDetail == null)
            {
                return View(nameof(UnknownID));
            }

            return View(moreDetail);
        }

        // GET: MoreDetails/Create
        public IActionResult Create()
        {
            ViewData["gID"] = new SelectList(_context.VideoGames, "gameID", "gameID");
            return View();
        }

        // POST: MoreDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("gID,description")] MoreDetail moreDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(moreDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["gID"] = new SelectList(_context.VideoGames, "gameID", "gameID", moreDetail.gID);
            return View(moreDetail);
        }

        // GET: MoreDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moreDetail = await _context.MoreDetails.FindAsync(id);
            if (moreDetail == null)
            {
                return NotFound();
            }
            ViewData["gID"] = new SelectList(_context.VideoGames, "gameID", "gameID", moreDetail.gID);
            return View(moreDetail);
        }

        // POST: MoreDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("gID,description")] MoreDetail moreDetail)
        {
            if (id != moreDetail.gID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(moreDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MoreDetailExists(moreDetail.gID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["gID"] = new SelectList(_context.VideoGames, "gameID", "gameID", moreDetail.gID);
            return View(moreDetail);
        }

        // GET: MoreDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moreDetail = await _context.MoreDetails
                .Include(m => m.gameID)
                .FirstOrDefaultAsync(m => m.gID == id);
            if (moreDetail == null)
            {
                return NotFound();
            }

            return View(moreDetail);
        }

        // POST: MoreDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moreDetail = await _context.MoreDetails.FindAsync(id);
            _context.MoreDetails.Remove(moreDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //UnknownID Page - Displays an error message
        public IActionResult UnknownID()
        {
            return View();
        }

        private bool MoreDetailExists(int id)
        {
            return _context.MoreDetails.Any(e => e.gID == id);
        }
    }
}

Controllers/VideoGamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NETD3202_Lab5_V3.Data;
using NETD3202_Lab5_V3.Models;

namespace NETD3202_Lab5_V3.Controllers
{
    public class VideoGamesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VideoGamesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VideoGames
        public async Task<IActionResult> Index()
        {
            return View(await _context.VideoGames.ToListAsync());
        }

        // GET: VideoGames/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videoGame = await _context.VideoGames
                .FirstOrDefaultAsync(m => m.gameID == id);
            if (videoGame == null)
            {
                return NotFound();
            }

            return View(videoGame);
        }

        // GET: VideoGames/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VideoGames/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("gameID,gameName,releaseYear,esrb,rating")] VideoGame videoGame)
        {
            if (ModelState.IsValid)
            {
                _context.Add(videoGame);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(videoGame);
        }

        // GET: VideoGames/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videoGame = await _context.VideoGames.FindAsync(id);
            if (videoGame == null)
            {
                return NotFound();
            }
            return View(videoGame);
        }

        // POST: VideoGames/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("gameID,gameName,releaseYear,esrb,rating")] VideoGame videoGame)
        {
            if (id != videoGame.gameID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(videoGame);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideoGameExists(videoGame.gameID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(videoGame);
        }

        // GET: VideoGames/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videoGame = await _context.VideoGames
                .FirstOrDefaultAsync(m => m.gameID == id);
            if (videoGame == null)
            {
                return NotFound();
            }

            return View(videoGame);
        }

        // POST: VideoGames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var videoGame = await _context.VideoGames.FindAsync(id);
            _context.VideoGames.Remove(videoGame);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VideoGameExists(int id)
        {
            return _context.VideoGames.Any(e => e.gameID == id);
        }
    }
}

Views/MoreDetails/Create.cshtml
<!--This page allows user to create a new MoreDetail object-->
@model NETD3202_Lab5_V3.Models.MoreDetail
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Create";
}
@if (SignInManager.IsSignedIn(User))
{
    <h4>Add More Detail</h4>
    <hr />
    <div>
        <div style="margin-left: 30%; margin-right: 30%">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="gID" class="control-label">Game ID</label>
                    <select asp-for="gID" class="form-control" asp-items="ViewBag.gID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="description" class="control-label">Description</label>
                    <textarea asp-for="description" class="form-control" placeholder="Storyline, concept, etc.">
                    </textarea>
                    <span asp-validation-for="description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div>
        <a style="color: black" asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
}
else
{
    <h1 class="display-4">Oops!</h1>
    <hr />
    <p class="lead">
        You don't have access to this page. Are you logged in?
    </p>

    <p class="lead">
        <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-lg btn-secondary">Login</a>
    </p>
}

Views/MoreDetails/Delete.cshtml
<!--This page allows user to delete an existing MoreDetail object-->
@model NETD3202_Lab5_V3.Models.MoreDetail
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Delete";
}
@if (SignInManager.IsSignedIn(User))
{
    <h1>Delete</h1>
    <hr />
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <hr />
        <dl>
            <dt>
                Game ID
            </dt>
            <dd>
                @Html.DisplayFor(model => model.gID)
            </dd>
            <dt>
                Description
            </dt>
            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="gID" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a style="color: black" asp-action="Index">Back to List</a>
        </form>
    </div>
}
else
{
    <h1 class="display-4">Oops!</h1>
    <hr />
    <p class="lead">
        You don't have access to this page. Are you logged in?
    </p>

    <p class="lead">
        <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-lg btn-secondary">Login</a>
    </p>
}

Views/MoreDetails/Details.cshtml
<!--This page allows user to view the details of a specific MoreDetails object-->
@model NETD3202_Lab5_V3.Models.MoreDetail
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Details";
}
@if (SignInManager.IsSignedIn(User))
{
    <div>
        <h4>Game ID: @Html.DisplayFor(model => model.gID) - Details</h4>
        <hr />
        <dl>
            <dt>
                Description
            </dt>
            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>
        </dl>
        <hr />
    </div>
    <div>
        <a style="color: black" asp-action="Edit" asp-route-id="@Model.gID">Edit</a>&nbsp;&nbsp;
        <a style="color: black" asp-controller="VideoGames" asp-action="Details" asp-route-id="@Model.gID">Other Details</a>&nbsp;&nbsp;
        <a style="color: black" asp-action="Index">More Details List</a>
    </div>
}
else
{
    <div>
        <h4>Game ID: @Html.DisplayFor(model => model.gID) - Details</h4>
        <hr />
        <dl>
            <dt>
                Description
            </dt>
            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>
        </dl>
        <hr />
    </div>
    <div>
        <a style="color: black" asp-controller="VideoGames" asp-action="Details" asp-route-id="@Model.gID">Other Details</a>&nbsp;&nbsp;
        <a style="color: black" asp-action="Index">More Details List</a>
    </div>
}

Views/MoreDetails/Edit.cshtml
<!--This page allows user to view the edit an existing MoreDetail objects-->
@model NETD3202_Lab5_V3.Models.MoreDetail
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Edit";
}
@if (SignInManager.IsSignedIn(User))
{
    <h4>Edit Video Game</h4>
    <hr />
    <div>
        <div style="margin-left: 30%; margin-right: 30%">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="gID" />
                <div class="form-group">
                    <label asp-for="gID" class="control-label">Game ID</label>
                    <input asp-for="gID" class="form-control" value="@Model.gID" disabled />
                    <span asp-validation-for="gID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="description" class="control-label">Description</label>
                    <textarea asp-for="description" class="form-control" placeholder="Storyline, concept, etc.">
                    </textarea>
                    <span asp-validation-for="description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div>
        <a style="color: black" asp-controller="VideoGames" asp-action="Index">Video Game List</a>&nbsp;&nbsp;
        <a style="color: black" asp-action="Index">More Details List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
}
else
{
    <h1 class="display-4">Oops!</h1>
    <hr />
    <p class="lead">
        You don't have access to this page. Are you logged in?
    </p>

    <p class="lead">
        <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-lg btn-secondary">Login</a>
    </p>
}

Views/MoreDetails/Index.cshtml
<!--This page allows user to view the list of MoreDetail objects-->
@model IEnumerable<NETD3202_Lab5_V3.Models.MoreDetail>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "List";
}
@if (SignInManager.IsSignedIn(User))
{
    <h1>More Details List</h1>
    <p>
        <a style="color: black" asp-action="Create">Add New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Game ID
                </th>
                <th>
                    Description
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.gameID.gameID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.gID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.gID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.gID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p class="lead">
        <a asp-controller="VideoGames" asp-action="Index" class="btn btn-lg btn-secondary">Video Game List</a>
    </p>
}
else
{
    <h1>More Details List</h1>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Game ID
                </th>
                <th>
                    Description
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.gameID.gameID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p class="lead">
        <a asp-controller="VideoGames" asp-action="Index" class="btn btn-lg btn-secondary">Video Game List</a>
    </p>
}

Views/MoreDetails/UnknownID.cshtml
<!--Used as an error displaying page for MoreDetails-->
    <h1 class="display-4">Oops!</h1>
    <hr />
    <p class="lead">
        Either the Game ID was not found or this Game ID is already on the additional details list. 
    </p>

    <p class="lead">
        <a asp-controller="MoreDetails" asp-action="Create" class="btn btn-lg btn-secondary">Try Again</a>
    </p>